application: snargecast
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /(.*\.(html|gif|png|jpg|ico|css|js))
  static_files: \1
  upload: (.*\.(html|gif|png|jpg|ico|css|js))
